spring.application.name=moneyServer

spring.datasource.url=jdbc:postgresql://localhost:port/dbname?currentSchema=schemaname
spring.datasource.username=user
spring.datasource.password=password

server.port=portNum
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379