spring.application.name=moneyServer

spring.datasource.url=jdbc:postgresql://localhost:5432/moneyserver?currentSchema=CREDITCARDTXNS
spring.datasource.username=postgres
spring.datasource.password=parthserver

server.port=9100

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=moneyserver